`quote_cabin_costs_id` integer auto_increment primary key not null,
`quote_id` integer not null,
`cabin_location` char(30) not null,
`cabin_type` varchar(255) not null,
`cabin_occupancy` integer not null,
`double_price` decimal(10,2) not null,
`cabins_held_count` integer not null,
`gl_add_on` decimal(10,2),
`insurance_cost` decimal(10,2),
`fc_double_cost` decimal(10,2),
`fc_single_cost` decimal(10,2),
`fc_multi_cost` decimal(10,2),
`co_double_cost` decimal(10,2),
`co_single_cost` decimal(10,2),
`co_multi_cost` decimal(10,2)