`quote_id` integer auto_increment primary key not null,
`ship_id` integer not null,
`cruise_line_id` integer not null,
`passenger_id` integer not null,
`user_id_preparer` integer not null,
`user_id_sales_rep` varchar(255) not null,
`sail_date` date not null,
`recall_date` date not null,
`final_balance_due_date` date not null,
`trip_date` date not null,
`prepared_date` date not null,
`cruise_line_group_num` varchar(255) not null,
`destination` varchar(255) not null,
`comp_policy` varchar(255) not null,
`bonus_points` varchar(255),
`nights_count` integer not null,
`flyer_doc_id` varchar(255) not null,
`cruise_contract_id` varchar(255) not null,
`proposal_doc_id` varchar(255) not null,
`comp_factor` integer not null default 0,
`deposit_amount_single` decimal(10,2),
`deposit_amount_double` decimal(10,2),
`airfare_cost` decimal(10,2),
`airtax_cost` decimal(10,2),
`gov_fees_cost` decimal(10,2),
`port_charges_cost` decimal(10,2),
`fuel_charge_cost` decimal(10,2),
`transfers_cost` decimal(10,2),
`pre-night_cost` decimal(10,2),
`pre-paid_tips_cost` decimal(10,2),
`air_deviation_cost` decimal(10,2),
`amenity_points_cost` decimal(10,2),
`motor_coach_cost` decimal(10,2),
`comp_factor_amount` decimal(10,2),
`gat_extra_cost` decimal(10,2),
`port_charges_credit` decimal(10,2),
`quote_fees_total_cost` decimal(10,2),
`credit_card_percentage` double not null,
`flyer_port_charges` decimal(10,2)




